### ISSUE TITLE
Global unity-like menu and window buttons.

### ISSUE THREAD

**Issue by stunito0o0o0** [linuxmint/linuxmint.github.io#10]
Hello, 
first I want to apologize if this is not the right place to put this, I am new to the github and linux world.
So I've been using Ubuntu for a couple of months, but then I found out about the mint distro with the cinnamon DE and I absolutely loved it... Everything is perfect so far except for the lack of unity-like global menu and window buttons. They are really helpful, especially when the window is maximized. I tried to resolve my problem by downlaoding 3rd party applets for the buttons, a global menu(@lestcape) and tried to configure them so they are as much as possible unity-like looking, but there are still problems. The buttons are sometimes glitchy, and the menu, well its awesome, but it doesn' work under root privileges.... So i basicly have to disable the menu applet everytime i open synaptic (to make the original menu show up) and then reanable it again once i'm done working under root. All this is annoying and it ruins the whole idea of having a replacement for the unity-like global menu. 
So basicly, I want to ask you put a option for a unity-like global menu and buttons in the next cinnamon release. I heard that the cinnamon is the most customizable DE so I hope that I can enjoy one more cusomatization in the near future.
Thank you all in advance for the great work :).

**Comment by JosephMcc** [comment]
This isn't the place, this would be: https://github.com/linuxmint/Cinnamon/issues
However, this same request has been made in the past and we have no intention of supporting it in Cinnamon ourselves. Searching the closed issues will turn up several issues for this already.
