### ISSUE TITLE
Ctrl+Alt+L does not work with desktop item selected

### ISSUE THREAD

**Issue by LEGOlord208** [linuxmint/linuxmint.github.io#11]
Like the title says. You can't have selected a desktop item for Ctrl+Alt+L to work.

**Comment by JosephMcc** [comment]
Ok, you need to provide better descriptions of your problems and some info about your system for this to be any use. I'm also a little confused about what it has to do with the developer site.

**Comment by LEGOlord208** [comment]
Sorry - It was on the wrong project... Please forgive me!
