### ISSUE TITLE
Please do not block tor on linuxmint.com!

### ISSUE THREAD

**Issue by juhiyu** [linuxmint/linuxmint.github.io#7]
@clefebvre 

Ever since Mint got sponsored with sucuri for the blog and websites, no one is able to post any message  through tor because the security blocks any TOR ips. Obviously I'm sure many users of Linux Mint are privacy-minded and would like to post feedback, ideas and questions on the blog and forums through Tor. Please allow Tor access to posting and viewing linuxmint.com forums and blog.

**Comment by juhiyu** [comment]
Tor still blocked on blog unable to provide feedback or bugs there..

**Comment by clefebvre** [comment]
Please raise this issue with Sucuri directly.
